# Generated by Django 5.2.9 on 2026-01-10 14:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be like +48123456789 or 123456789', regex='^\\+?[0-9]{7,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)])),
                ('model', models.CharField(max_length=80)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('potential_sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'unique_together': {('manufacturer', 'year', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('actual_sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='dealership.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='dealership.employee')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
    ]
